- hosts: all
  vars:
      mounting_folder: "dvd"
  tasks:
    - name: "Creating mounting folder for dvd"
      file:
          path: "/{{ mounting_folder }}"
          state: directory

    - name: "Mounting dvd in folder"
      mount:
          path: "/{{ mounting_folder }}"
          src: "/dev/sr0"
          fstype: "iso9660"
          state: mounted
          opts: ro


    - name: "yum config for AppStream"
      yum_repository:
          name: "AppStream"
          baseurl: "/{{ mounting_folder }}/AppStream"
          gpgcheck: false
          enabled: true
          description: "AppStream-repo"

    - name: "yum config for BaseOS"
      yum_repository:
          name: "BaseOS"
          baseurl: "/{{ mounting_folder }}/BaseOS"
          gpgcheck: false
          enabled: true
          description: "BaseOS-repo"

